services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 969080op
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 3000:3000
      
    volumes:
      - db_data:/var/lib/postgresql
volumes:
    db_data: