import type { Metadata } from "next";

import "../../../globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import { Roboto } from 'next/font/google';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
      <body
        className={roboto.className}
      >
       
        {children}

      </body></ClerkProvider>
    </html>
  );
}
