import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider, SignedOut, SignIn, SignedIn } from "@clerk/nextjs";

import { Roboto } from 'next/font/google';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <ClerkProvider>
        <body className="antialiased">
          <SignedOut>
            <div className="flex h-screen justify-center items-center">
              <h2>If you are a new user, please click Sign Up</h2>
              <SignIn />
            </div>
          </SignedOut>

          <SignedIn>
            {children}
          </SignedIn>
        </body>
      </ClerkProvider>
    </html>
  );
}
